name: GitHub Actions Tests Group
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
      - run: npm run lint:scss
  Unit:
    runs-on: ubuntu-latest
    steps:
      - run: npm run test:unit
  UI:
    runs-on: ubuntu-latest
    steps:
      - run: npm run test:ui:ci
